(in-package :g1)

(defvar *constellations*
  '(("Antlia" "Antilae")
    (nil "Aquarii")
    ("Aquila" "Aquilae")
    (nil "Arietis")
    ("Auriga" "Aurigae")
    ("Caelum" "Caeli")
    (nil "Camelopardalis")
    ("Caprica" "Capricorni")
    ("Carina" "Carinae")
    ("Cassiopeia" "Cassiopeiae")
    ("Cepheus" "Cephei")
    ("Cetus" "Ceti")
    ("Circinus" "Circini")
    ("Columba" "Columbae")
    ("Corvus" "Corvi")
    (nil "Crateris")
    ("Crux" "Crucis")
    ("Cygnus""Cygni")
    ("Delphinus" "Delphini")
    ("Draco" "Draconis")
    (nil "Eridani")
    (nil "Gruis")
    (nil "Herculis")
    ("Hydrus" "Hydrae")
    ("Indus" "Indi")
    ("Leo" "Leonis")
    ("Lepus" "Leporis")
    ("Libra" "Librae")
    ("Lyra" "Lyrae")
    ("Octans" "Octanis")
    ("Ophiucus" "Ophiuchii")
    ("Orion" "Orionis")
    ("Pavo" "Pavonis")
    ("Pegasus" "Pegasi")
    ("Perseus" "Persei")
    ("Pictor" "Pictoris")
    ("Reticulum" "Reticuli")
    (nil "Sagittari")
    ("Scorpuis" "Scorpii")
    ("Sculptor" "Sculptoris")
    ("Serpens" "Serpentis")
    ("Sextans" "Sextanis")
    ("Taurus" "Tauri")
    ("Ursa" "Ursae")
    ("Vela" "Velorum")
    ("Volans" "Volantis")
    ("Vulpecula" "Vulpeculae")
    ("Corrin" "Corrino")
    ("Nebia")
    ("Polaris")
    ("Sirius")
    ("Betelgeuse")
    ("Canopus")
    ("Arcturus")
    ("Rigel")
    ("Procyon")
    ("Altair")
    ("Aldebaran")
    ("Spica")
    ("Antares")
    ("Pollux")
    ("Deneb")
    ("Mimosa")
    ("Regulus")
    ("Bellatrix")
    ("Alioth")
    ("Alphard")
    ("Murzim")
    ("Saiph")
    ("Nunki")
    ("Alpheratz")
    ("Kochab")
    ("Algol")
    ("Naos")
    ("Etamin")
    ("Mizar")
    ("Wei")
    ("Markab")
    ("Gienah")
    ("Aludra")
    ("Hoth")
    ("Eddington")
    ("Bermudis")
    ("Groombridge")
    ("Gliese")
    ("Doradus")
    ("Zora")
    ("Deckard")
    ("Tyrell")
    ("Luyten")
    ("Teegarden")
    ("Bessel")
    ("Kepler")
    ("Tycho")
    ("Diphda")
    ("Menkar")
    ("Capella")
    ("Adhara")
    ("Dubhe")
    ("Acrux")
    ("Alkaid")
    ("Atria")
    ("Sabik")
    ("Shaula")
    ("Enif")
    ("Lieb")
    ("Elantis")
    ("Mattis")
    ("Ohm")
    ("Watts")
    ("Compton")
    ("Albertis")
    ("Ofu")
    ("Kosrae")
    ("Ulithi")
    ("Puluwat")
    ("Atiu")
    ("Mitiaro")
    ("Nassau")
    ("Rotuma")
    ("Kadavu")
    ("Tupai")
    ("Majuro")
    ("Apolima")
    ("Ulawa")
    ("Ambrym")
    ("Alofi")
    ("Milne")
    ("Zhokhov")
    ("Akane")
    ("Nataree")
    ("Poseidon")
    ("Zeus")
    ("Ares")
    ("Athena")
    ("Demeter")
    ("Hades")
    ("Hera")
    ("Hestia")
    ("Erebus")
    ("Zephyrus")
    ("Themis")
    ("Atlas")
    ("Hyperion")
    ("Prometheus")
    ("Ophion")
    ("Plato")
    ("Sandoz")
    ("Hoffman")
    ("McCarthy")
    ("Bespin")
    ("Endor")
    ("Yavin")
    ("Kraken")
    ("Baccus")  
    ("Melmac")
    ("Magrathea")
    ("Folfanga")
    ("Frogstar")
    ("Hastromil")
    ("Babel")
    ("Vulcan")
    ("Artemis")
    ("Brutus")
    ("Xenon")
    ("Siam")
    ("Rama")
    ("Lennon")
    ("Levin")
    ("Karenina")
    ("Karamazov")
    ("Oberon")
    ("Titania")
    ("Puck's Star")
    ("Lysander")
    ("Hermia")
    ("Philostrate")
    ("Laertes")
    ("Osric")
    ("Rosencrantz")
    ("Guildenstern")
    ("Fortinbras")
    ("Lucius")
    ("Greenblatt")
    ("Belzagor")
    ("Chiron")
    ("Dosadi")
    ("Erna")
    ("Irata")
    ("Ishtar")
    ("Kinmoku")
    ("Kharak")
    ("Lumen")
    ("Nihil")
    ("Nirn")
    ("Pandora")
    ("Pharagos")
    ("Ragnarok")
    ("Sauria")
    ("Stroggos")
    ("Tirol")
    ("Marklar")
    ("Remulak")
    ("Al Dhanab")
    ("Caladan")
    ("Wallach")
    ("Giedi")
    ("Hagal")
    ("Kaitain")
    ("Naraj")
    ("Romo")
    ("Tleilax")
    ("Thalim")
    ("Albion")
    ("Zanzibar")
    ("Garland")
    ("Matoya")
    ("Astos")
    ("Sarda")
    ("Lefein")
    ("Gallifrey")
    ("Skaro")
    ("Mondas")
    ("Vortis")
    ("Romana")
    ("Landen")
    ("Aridia")
    ("Elysium")
    ("Alzarius")
    ("Argolis")
    ("Atrios")
    ("Boromeo")
    ("Calufrax")
    ("Cassius")
    ("Castrovalva")
    ("Exxilon")
    ("Lelex")
    ("Kylos")
    ("Kosnax")
    ("Lurma")
    ("Marinus")
    ("Minyos")
    ("Navarro")
    ("Raga")
    ("Sontar")
    ("Tara")
    ("Zanak")
    ("Zeos")
    ("Kardashev")
    ("Sivar")
    ("Enyo")
    ("McAuliffe")
    ("Brimstone")
    ("Rostov")
    ("Kurasawa")
    ("Venice")
    ("Midgard")
    ("Jotunheim")
    ("Goddard")
    ("Caspar")
    ("Kyabetsu")
    ("Syra")
    ("Styx")
    ("Echo")
    ("Momus")
    ("Khitomer")
    ("Tarazed")
    ("Caph")
    ("Thuban")
    ("Arneb")
    ("Mintaka")
    ("Nath")
    ("Phaeda")
    ("Ascella")
    ("Wesen")
    ("Gemma")
    ("Hamal")
    ("Megrez")
    ("Lain")
    ("Gwynedd")
    ("Enigma")
    ("Tesla")
    ("Niven")
    ("Pembroke")
    ("Thrakkath")
    ("Orsini")
    ("Vespus")
    ("Zelazny")
    ("Hellespont")
    ("Gemini")
    ("Troy")
    ("Rhombus")
    ("Isis")
))

(defun constellation-name-list ()
  (copy-list *constellations*))


(defun planet-type-description (planet-type)
  (ecase planet-type
    (terran   "Terran Habitat")
    (oceanic  "Oceanic Habitat")
    (jungle   "Jungle Habitat")
    (arid     "Arid Habitat")
    (desert   "Desert Habitat")
    (tundra   "Tundra Habitat")
    (minimal  "Minimal Habitat")
    (barren   "Barren World")
    (volcanic "Volcanic World")
    (dead     "Dead World")
    (inferno  "Inferno World")
    (toxic    "Toxic World")
    (radiated "Radiated World")))
